intégration du form+NewsLetter
WildCodeSchool-2023-09/JS-RMT-React_If-Projet2-Bear_beers pull request #6
Opened 2023-11-08 09:07 UTC by Skiln3zz

2023-11-08 13:34 UTC, Unictium approved these changes

2023-11-08 13:37 UTC, ZeEleveZozo approved these changes

2023-11-09 10:15 UTC, jujuck requested changes

2023-11-09 10:15 UTC, jujuck commented on frontend/src/components/Form.jsx
> +  const [Nom, setNom] = useState("");
Respect de la convention de nommage [nom, setNom]... Pas de majuscule pour commencer le nom des variables

2023-11-09 10:15 UTC, jujuck commented on frontend/src/components/Form.jsx
> +  const [Prenom, setPrenom] = useState("");
idem

2023-11-09 10:15 UTC, jujuck commented on frontend/src/components/Form.jsx
> +  const [Email, setEmail] = useState("");
Idem

2023-11-09 10:15 UTC, jujuck commented on frontend/src/components/Form.jsx
> +  const [Biere, setBiere] = useState("Bière1");
Idem

2023-11-09 10:15 UTC, jujuck commented on frontend/src/components/Form.jsx
> +        <input
En react on intègre directement l'input dans le label. Cela permet de supprimer les htmlFor et les id sur input
<label>
Mon Label...
<input>
</label>

2023-11-09 10:15 UTC, jujuck commented on frontend/src/components/Form.jsx
> +        <br />
On va privilégie du css pour faire l'espacement (via margin-bottom)

2023-11-09 10:15 UTC, jujuck commented on frontend/src/components/Form.jsx
> +        <label htmlFor="prenom">Prénom :</label>
Idem label / input

2023-11-09 10:15 UTC, jujuck commented on frontend/src/components/Form.jsx
> +        <label htmlFor="email">Adresse e-mail :</label>
Idem label / input

2023-11-09 10:15 UTC, jujuck commented on frontend/src/components/Form.jsx
> +        <label htmlFor="biere">Choix de bière préférée :</label>
Idem label / input

2023-11-09 10:15 UTC, jujuck commented on frontend/src/components/Form.jsx
> +        <input type="submit" value="Enregistrer" />
ON va privilégié un bouton de type submit

2023-11-09 10:15 UTC, jujuck commented on frontend/src/components/Form.jsx
> +    e.preventDefault();
On va finir le handle submit (via emailJs ou autre stack)

2023-11-14 08:22 UTC, jujuck approved these changes

2023-11-14 08:40 UTC, merged